### ISSUE TITLE
tldr: Error in quoting command names

### ISSUE THREAD

**Issue by aftix** [carapace-sh/carapace-bin#2342]
### Current Behavior

I'm using [tealdeer](https://github.com/dbrgn/tealdeer), a tldr client. Carapace uses `tldr -l` to get a list of commands in the tldr documentation database, but the command returns names that need to be quoted such as `!` and `[`. As a result, tab completion on tldr gives an error instead of providing completions.

### Expected Behavior

carapace should correctly quote these command names so that tab completion works as expected.

### Steps To Reproduce

1. Build carapace from master
2. Install tealdeer
3. Run `carapace tldr bash ''`
4. carapace returns `trueERR\n-`

I have tried with every available shell, and they all return their own flavor of "ERR".

EDIT: I have tried with `tlrc`(the official tldr client) and the same thing happens

### Version

master

### OS

- [X] Linux
- [ ] OSX
- [ ] Windows

### Shell

- [ ] Bash
- [X] Elvish
- [ ] Fish
- [ ] Nushell
- [ ] Oil
- [ ] Powershell
- [ ] Xonsh
- [ ] Zsh

**Comment by rsteube** [comment]
Urks. So the issue here is that there are multiple [clients](https://github.com/tldr-pages/tldr/wiki/tldr-pages-clients#console-clients) that all use the binary name `tldr` :roll_eyes: and have different behaviour.
The current completer was written for the python version which is installed by the `tldr` package in arch/manjaro.

**Comment by aftix** [comment]
I spun up a venv and saw the python tldr has a much different output than the others. Could there be completers for say `tealdeer` and `tlrc` and have it be up to the user to set the right completion command in their rc file?

**Comment by rsteube** [comment]
Yes. I've been meaning to put together a concept for this for a while now as some core tools differ between distros.
It's pretty simple though. Just deciding where to put it and updating some code here and there.

[User specs](https://carapace-sh.github.io/carapace-bin/spec/user.html) override internal completers so that could be used as workaround in the meantime.

**Comment by aftix** [comment]
Are you open to a PR adding `completers/tealdeer_completer` for now?

**Comment by rsteube** [comment]
Yeah, can do that. Got one here: https://github.com/carapace-sh/carapace-bin/pull/2345/files
Just copy it  to `tealdeer_completer` and the action for a new pr.
